/*1A.FORMA NORMAL*/

/*
1-TODO CAMPO VETORIZADO SE TORNARA OUTRA TABELA.

2-TODO CAMPO MULTIVALORADO SE TORNARA OUTRA TABELA.

3-TODA TABELA NECESSITA DE PELO MENOS UM CAMPO QUE 
  IDENTIFIQUE TODO O REGISTRO COMO SENDO UNICO.