/*MODELAGEM*/
/*------------------------------*/
/*RASCUNHO*/
/*MODELAGEM CONCEITUAL*/
/*CRIANDO DATABASE*/
	DATABASE PROJETO1;

/*CRIANDO TABELA*/
	TABELA CLIENTE1
		NOME VARCHAR(30)
		ENDERECO VARCHAR (100)
		TELEFONE INT (11)

/*------------------------------*/
/*MODELAGEM LOGICA*/
BRMODELO


/*------------------------------*/
/*MODELAGEM FISICA*/
/*1-CRIANDO O BANCO DE DADOS*/
	CREATE DATABASE PROJETO1;
	
/*2-CONECTANDO AO BANCO DE DADOS*/
	USE PROJETO1;
	
/*3-CRIANDO A TABELA E OS ATRIBUTOS*/
	CREATE TABLE CLIENTE1(
		NOME VARCHAR(30),
		ENDERECO VARCHAR(100),
		TELEFONE VARCHAR(30)
	);

/*------------------------------*/	
/* VERIFICANDO AS TABELAS */

SHOW TABLES;

/*------------------------------*/
/* DESCREVENDO AS TABELAS */

DESC CLIENTE;
	
/*------------------------------*/

/*A1.FORMA NORMAL*/

/*
1-TODO CAMPO VETORIZADO SE TORNARA OUTRA TABELA.

2-TODO CAMPO MULTIVALORADO SE TORNARA OUTRA TABELA.

3-TODA TABELA NECESSITA DE PELO MENOS UM CAMPO QUE 
  IDENTIFIQUE TODO O REGISTRO COMO SENDO UNICO.
  
*/
 
/*------------------------------*/

 /* Modelagem basica */

/* PROCESSO DE MODELAGEM

-- CRIADO PELO ADM. DE DADOS --

- MODELAGEM CONCEITUAL - RASCUNHO

- MODELAGEM LOGICA - PROGRAMAS COMO BRMODELO

-- CRIADO PELO ADM. DE DADOS OU PELO DBA --

- MODELAGEM FISICA - SCRIPT DO BANCO

*/

/*------------------------------*/

/*COMANDO SELECT*/
	
	SELECT NOW();

/*------------------------------*/

/*OPERADORES LOGICOS*/
/*OR - OU*/

	SELECT NOME, EMAIL FROM CLIENTE
	WHERE
	SEXO = 'M' OR ENDERECO LIKE '%RJ';
	
	SELECT NOME, EMAIL FROM CLIENTE
	WHERE
	SEXO = 'F' OR ENDERECO LIKE '%ESTACIO';
	
/*AND - E*/

	SELECT NOME, EMAIL FROM CLIENTE
	WHERE
	SEXO = 'M' AND ENDERECO LIKE '%RJ';
	
	SELECT NOME, EMAIL FROM CLIENTE
	WHERE
	SEXO = 'F' AND ENDERECO LIKE '%ESTACIO';

/*------------------------------*/



/*------------------------------*/