/*A23-QUERIES*PROJECAO-JUNCAO-SELECAO*/
/*
PARA UMA CAMPANHA DE MARKETING, O SETOR SOLICITOU UM
RELATORIO COM O NOME, EMAIL E TELEFONE CELULAR
DOS CLIENTES QUE MORAM NO ESTADO DO RIO DE JANEIRO.
VOCE TERA QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA
O PROGRAMADOR
*/

/*QUERY*/
/*PROJECAO*/
SELECT C.NOME, C.EMAIL, T.NUMERO
FROM CLIENTE C

/*JUNCAO*/
/*JUNCAO TABELA TELEFONE*/
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
/*JUNCAO TABELA ENDERECO*/
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE

/*SELECAO*/
WHERE TIPO = 'CEL' AND ESTADO = 'RJ';

+---------+----------------+---------+
| NOME    | EMAIL          | NUMERO  |
+---------+----------------+---------+
| JOAO    | JOAO@IG.COM    | 3456789 |
| JOAO    | JOAO@IG.COM    | 2334567 |
| ANTONIO | NULL           | 3456789 |
| ANTONIO | NULL           | 8768790 |
| CELIA   | JOAO@TERRA.COM | 1345435 |
+---------+----------------+---------+

/*--------------------------------------------------------------------*/
/*
	PARA UMA CAMPANHA DE PRODUTOS DE BELEZA, O COMERCIAL SOLICITOU UM
	RELATORIO COM O NOME, EMAIL, E TELEFONE CELULAR
	DAS MULHERES QUE MORAM NO ESTADO DE SAO PAULO.
	VOCE TERA QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA
	O PROGRAMADOR.
*/
/*--------------------------------------------------------------------*/

/*QUERY*/
/*PROJECAO*/
SELECT C.NOME, C.EMAIL, T.NUMERO
FROM CLIENTE C

/*JUNCAO*/
/*JUNCAO TABELA TELEFONE*/
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE

/*JUNCAO TABELA ENDERECO*/
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE

/*SELECAO*/
WHERE TIPO = 'CEL' AND SEXO = 'F' AND ESTADO = 'SP';

+------+---------------+---------+
| NOME | EMAIL         | NUMERO  |
+------+---------------+---------+
| ANA  | ANA@GLOBO.COM | 3987698 |
+------+---------------+---------+

/*COMANDO IFNULL*/

/*QUERY*/
/*PROJECAO*/
SELECT C.NOME, C.EMAIL, T.NUMERO
FROM CLIENTE C

/*JUNCAO*/
/*JUNCAO TABELA TELEFONE*/
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
/*JUNCAO TABELA ENDERECO*/
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE

/*SELECAO*/
WHERE TIPO = 'CEL' AND ESTADO = 'RJ';





















