/*A24-VIEWS OU VISOES*/
/*VIEWS SAO MUITO UTILIZADAS POR DBA E AD*/

/*QUERY*/
/*PROJECAO*/
SELECT C.NOME,
	   C.SEXO,
	   IFNULL(C.EMAIL, "SEM E-MAIL") AS "E-MAIL", /*TABELA CLIENTE*/
	   T.TIPO,
	   T.NUMERO, /*TABELA TELEFONE*/
	   E.BAIRRO,
	   E.CIDADE,
	   E.ESTADO /*TABELA ENDERECO*/
FROM CLIENTE C
/*JUNCAO*/
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE;

/*CRIANDO A VIEW*/

CREATE VIEW RELATORIO AS
/*QUERY*/
/*PROJECAO*/
SELECT C.NOME,
	   C.SEXO,
	   IFNULL(C.EMAIL, "SEM E-MAIL") AS "E-MAIL", /*TABELA CLIENTE*/
	   T.TIPO,
	   T.NUMERO, /*TABELA TELEFONE*/
	   E.BAIRRO,
	   E.CIDADE,
	   E.ESTADO /*TABELA ENDERECO*/
FROM CLIENTE C
/*JUNCAO*/
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE;

/*APRESENTAR A VIEW*/
SELECT * FROM RELATORIO;

/*CRIAR SELECAO DENTRO DA VIEW*/
SELECT * FROM RELATORIO
WHERE SEXO = 'F';

/*ATUALIZAR TABELA CLIENTE*/
/*A CLIENTE CELIA ESTA COM O ENDERECO DE E-MAIL ERRADO*/
UPDATE CLIENTE
SET EMAIL = 'CELIA@TERRA.COM,BR'
WHERE IDCLIENTE = 6; /*SELECAO*/

/*VISUALIZANDO TODAS AS TABELAS E VIEWS*/
/*RELATORIO E UMA VIEW*/
SHOW TABLES;
+--------------------+
| Tables_in_comercio |
+--------------------+
| cliente            |
| endereco           |
| relatorio          |
| telefone           |
+--------------------+

/*CRIANDO PADRAO PARA NOMEAR AS VIEWS*/
CREATE VIEW V_RELATORIO AS
/*QUERY*/
/*PROJECAO*/
SELECT C.NOME,
	   C.SEXO,
	   IFNULL(C.EMAIL, "SEM E-MAIL") AS "E-MAIL", /*TABELA CLIENTE*/
	   T.TIPO,
	   T.NUMERO, /*TABELA TELEFONE*/
	   E.BAIRRO,
	   E.CIDADE,
	   E.ESTADO /*TABELA ENDERECO*/
FROM CLIENTE C
/*JUNCAO*/
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE;

/*APAGANDO A VIEW DO BANCO DE DADOS*/
/*COMANDO DROP VIEW*/
DROP VIEW RELATORIO;

/*CRIANDO A VIEW COM PADRAO "V_" ANTES DO NOME DO RELATORIO OU VIEW*/
/*CRIANDO PADRAO PARA NOMEAR AS VIEWS*/
CREATE VIEW V_RELATORIO AS
/*QUERY*/
/*PROJECAO*/
SELECT C.NOME,
	   C.SEXO,
	   IFNULL(C.EMAIL, "SEM E-MAIL") AS "E-MAIL", /*TABELA CLIENTE*/
	   T.TIPO,
	   T.NUMERO, /*TABELA TELEFONE*/
	   E.BAIRRO,
	   E.CIDADE,
	   E.ESTADO /*TABELA ENDERECO*/
FROM CLIENTE C
/*JUNCAO*/
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE;

/*CRIANDO PROJECAO NA VIEW*/
SELECT NOME, SEXO, CIDADE
FROM V_RELATORIO;

+---------+------+----------------+
| NOME    | SEXO | CIDADE         |
+---------+------+----------------+
| JOAO    | M    | RIO DE JANEIRO |
| JOAO    | M    | RIO DE JANEIRO |
| JOAO    | M    | RIO DE JANEIRO |
| CARLOS  | M    | B. HORIZONTE   |
| ANA     | F    | SAO PAULO      |
| ANA     | F    | SAO PAULO      |
| CELIA   | F    | NITEROI        |
| CELIA   | F    | NITEROI        |
| CELIA   | F    | NITEROI        |
| ANTONIO | M    | RIO DE JANEIRO |
| ANTONIO | M    | RIO DE JANEIRO |
| ANTONIO | M    | RIO DE JANEIRO |
+---------+------+----------------+

/*DELETANDO A PARTIR DA VIEW*/
DELETE FROM V_RELATORIO
WHERE NOME = 'JOAO';

/*ERRO AO TENTAR DELETAR REGISTROS A PARTIR DA VIEW*/
ERROR 1395 (HY000): Can not delete from join view 'comercio.v_relatorio'

/*INSERINDO DADOS A PARTIR DA VIEW*/
INSERT INTO V_RELATORIO VALUES
('ROMARIO', 'M', NULL, 'RES', '99723882', 'BARRA', 'RIO DE JANEIRO', 'RJ');

/*ERRO AO TENTAR INSERIR REGISTROS A PARTIR DA VIEW*/
ERROR 1394 (HY000): Can not insert into join view 'comercio.v_relatorio' without fields list






















