/*A26 - DELIMITADOR E ESTADO DE SERVIDOR*/

SELECT * FROM CLIENTE; /*O ';' E O DELIMITADOR*/

/*ALTERAR O DELIMITADOR*/

DELIMITER $

SELECT * FROM CLIENTE$

/*O ESTADO DO SERVIDOR E CONSEGUIDO ATRAVES DO COMANDO STATUS*/

STATUS;

/*ERROS COMUNS NO DELIMITER*/

NAO COLOCAR ESPACO APOS A PALAVRA RESERVADA DELIMITER
