/*A30 - AGREGANDO COM A FUNCAO SUM*/
/*SOMA TOTAL DE VENDAS DO MES JANEIRO PARA TABELA VENDEDORES*/
SELECT SUM(JANEIRO) AS 'TOTAL JANEIRO'
FROM VENDEDORES;

/*SOMA TOTAL DE VENDAS DOS MESES DE JANEIRO, FEVEREIRO E MARCO, PARA A TABELA VENDEDORES*/
SELECT SUM(JANEIRO) AS 'TOTAL JANEIRO',
	   SUM(FEVEREIRO) AS 'TOTAL FEVEREIRO',
	   SUM(MARCO) AS 'TOTAL MARCO'
FROM VENDEDORES;	   

/*SOMA DAS VENDAS POR SEXO PARA O MES DE MARCO*/
SELECT SEXO, SUM(MARCO) AS 'TOTAL MARCO'
FROM VENDEDORES
GROUP BY SEXO;

/*--------------------*/
/*TOTAL DAS VENDAS DOS MESES DE JANEIRO, FEVEREIRO E MARCO*/
SELECT SUM(JANEIRO) AS "TOTAL JANEIRO",
	   SUM(FEVEREIRO) AS "TOTAL FEVEREIRO",
	   SUM(MARCO) AS "TOTAL MARCO"
FROM VENDEDORES;

/*SOMA DAS VENDAS POR SEXO PARA O MES DE MARCO*/
SELECT SEXO, SUM(MARCO) AS "TOTAL MARCO"
FROM VENDEDORES
GROUP BY SEXO;