/*A31 - SUBQUERIES*/

SELECT MIN(MARCO) FROM VENDEDORES;

SELECT NOME, MARCO FROM VENDEDORES;

/*A31 - VENDEDOR QUE VENDEU MENOS EM MARCO E SEU NOME*/
SELECT NOME, MARCO
FROM VENDEDORES
WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEDORES);

/*A31 - VENDEDOR QUE VENDEU MAIS EM MARCO E SEU NOME*/
SELECT NOME, MARCO
FROM VENDEDORES
WHERE MARCO = (SELECT MAX(MARCO) FROM VENDEDORES);

/*A31 - VENDEDOR QUE VENDEU MAIS QUE MEDIA EM FEVEREIRO*/
SELECT NOME, FEVEREIRO
FROM VENDEDORES
WHERE FEVEREIRO > (SELECT AVG(FEVEREIRO) FROM VENDEDORES);

SELECT NOME, MARCO
FROM VENDEDORES
WHERE MARCO > (SELECT AVG(MARCO) FROM VENDEDORES);