/*A32 - OPERACOES EM LINHA*/

SELECT * FROM VENDEDORES;

/*SOMA DAS VENDAS POR TRIMESTRE PARA OS VENDEDORES*/
SELECT NOME,
	   JANEIRO,
	   FEVEREIRO,
	   MARCO,
	   (JANEIRO+FEVEREIRO+MARCO) AS "TOTAL TRIMESTRE",
	   TRUNCATE((JANEIRO+FEVEREIRO+MARCO)/3,2) AS "MEDIA"
	   FROM VENDEDORES;	   