/*A34 - ORGANIZACAO DE CHAVES - CONSTRAINT (REGRA)*/

/*CRIANDO A TABELA JOGADOR*/

CREATE TABLE JOGADOR(
	IDJOGADOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30)
);

/*CRIANDO A TABELA TIMES*/

CREATE TABLE TIMES(
	IDTIMES INT PRIMARY KEY AUTO_INCREMENT,
	NOMETIME VARCHAR(30),
	ID_JOGADOR INT,
	FOREIGN KEY(ID_JOGADOR)
	REFERENCES JOGADOR(IDJOGADOR)
);

/*INSERINDO REGISTRO NA TABELA JOGADOR*/

INSERT INTO JOGADOR VALUES (NULL, 'GUERRERO');
INSERT INTO TIMES VALUES (NULL, 'FLAMENGO', 1);