/*A40 - PRATICA - REFAZENDO A AULA 40*/

/*O CENARIO E: TODA VEZ QUE EU APAGAR UM REGISTRO 
DA TABELA USUARIO, QUERO QUE O REGISTRO SEJA BACKUPADO
IMEDIATAMENTE*/

/*CRIANDO A DATABASE*/
CREATE DATABASE AULA41;

/*INICIANDO A DATABASE AULA41*/
USE AULA41;

/*CRIANDO TABELA USUARIO*/
CREATE TABLE USUARIO(
	IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	LOGIN VARCHAR(30),
	PASSWORD VARCHAR(100)
);

/*CRIANDO TABELA BACKUP DA USUARIO*/
CREATE TABLE BKP_USUARIO(
	IDBKP_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
	IDUSUARIO INT,
	NOME VARCHAR(30),
	LOGIN VARCHAR(30)
);

/*ALTERANDO O DELIMITER*/
DELIMITER $

/*CRIANDO A TRIGGER*/
/*TRIGGER INSERE REGISTRO NA TABELA BKP_USUARIO,
 ANTES DE DELETAR O REGISTRO DA TABELA USUARIO*/
 
 CREATE TRIGGER BKP_USER
 BEFORE DELETE ON USUARIO
 FOR EACH ROW
 BEGIN
 
	INSERT INTO BKP_USUARIO VALUES(NULL, OLD.IDUSUARIO, OLD.NOME, OLD.LOGIN);
	
END
$

/*RETORNANDO O DELIMITER*/
DELIMITER ;

/*INSERINDO REGISTROS NA TABELA USUARIO*/
INSERT INTO USUARIO VALUES(NULL, 'ANDRADE', 'ANDRADE2009', 'HEXACAMPEAO');

/*DELETANDO REGISTRO DA TABELA USUARIO*/
DELETE FROM USUARIO WHERE IDUSUARIO = 1;

/*VERIFICANDO NA TABELA BKP_USUARIO*/
SELECT * FROM BKP_USUARIO;