/*A44-AUTORELACIONAMENTO*/
/*CRIANDO DATABASE AULA44*/
CREATE DATABASE AULA44;

USE AULA44;

/*CRIANDO A TABELA CURSOS*/
CREATE TABLE CURSOS(
	IDCURSOS INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	HORAS INT,
	VALOR FLOAT(10,2),
	ID_PREREQ INT
);

/*OBSERVACAO - PARA ORGANIZAR MELHOR, PODEMOS INSERIR O CURSO 'SEM PREREQ'
PODEMOS CRIAR OS DADOS DE 1: NAO INFORMADO - 2: NAO SE APLICA
PARA BANCOS DE DADOS*/
INSERT INTO CURSOS VALUES(1,'SEM PREREQ', 0, 0.0, NULL);

/*CRIANDO A CHAVE ESTRANGEIRA*/
ALTER TABLE CURSOS ADD CONSTRAINTS FK_PREREQ
FOREIGN KEY(ID_PREREQ) REFERENCES CURSOS(IDCURSO);

/*INSERINDO DADOS NA TABELA*/
INSERT INTO CURSOS VALUES(NULL, 'BD RELACIONAL', 20, 400, NULL);
INSERT INTO CURSOS VALUES(NULL, 'BD RELACIONAL', 20, 800, 1);
INSERT INTO CURSOS VALUES(NULL, 'RELATORIO AVANCADOS', 20, 600, 2);
INSERT INTO CURSOS VALUES(NULL, 'LOGICA PROGR', 20, 400, NULL);
INSERT INTO CURSOS VALUES(NULL, 'RUBY', 30, 500, 4);

/*OBSERVACAO: INSERIR FISICO*/

ALTER TABLE CURSOS ADD CONSTRAINTS FK_PREREQ
FOREIGN KEY(ID_PREREQ) REFERENCES CURSOS(IDCURSOS);