/*CARDINALIDADE*/

/*QUEM DEFINE A CARDINALIDADE E A REGRA DE NEGOCIOS*/

/*
PRIMEIRO ALGARISMO - OBRIGATORIEDADE

0 - NAO OBRIGATORIO
1 - OBRIGATORIO

SEGUNDO ALGARISMO - CARDINALIDADE
1 - MAXIMO DE UM
N - MAIS DE UM

*/