/* Modelagem basica */

/* PROCESSO DE MODELAGEM

-- CRIADO PELO ADM. DE DADOS --

- MODELAGEM CONCEITUAL - RASCUNHO

- MODELAGEM LOGICA - PROGRAMAS COMO BRMODELO

-- CRIADO PELO ADM. DE DADOS OU PELO DBA --

- MODELAGEM FISICA - SCRIPT DO BANCO

*/

/* MODELAGEM CONCEITUAL - RASCUNHO - FASE 01 */

CLIENTE

NOME CARACTER(30)
CPF NUMERICO(11)
EMAIL CARACTER (30)
TELEFONE CARACTER (30)
SEXO CARACTER (1)
ENDERECO CARACTER (100)

/* MODELAGEM LOGICA - PROGRAMAS COMO BRMODELO

CRIADO MODELO LOGICO NO BRMODELO 

*/

/* MODELAGEM FISICA - SCRIPT DO BANCO DE DADOS

/* CRIANDO UM BANCO DE DADOS */

CREATE DATABASE PROJETO;

/* CONECTANDO */

USE PROJETO;

/* CRIANDO A TABELA */

CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);

/* VERIFICANDO AS TABELAS */

SHOW TABLES;

/* DESCREVENDO AS TABELAS */

DESC CLIENTE;