/*MODELAGEM BASICA*/

/* PROCESSO DE MODELAGEM

-- CRIADO PELO ADM. DE DADOS --

- MODELAGEM CONCEITUAL - RASCUNHO

- MODELAGEM LOGICA - PROGRAMAS COMO BRMODELO

-- CRIADO PELO ADM. DE DADOS OU PELO DBA --

- MODELAGEM FISICA - SCRIPT DO BANCO

*/