/*OPERADORES LOGICOS*/
/*OR - OU*/

	SELECT NOME, EMAIL FROM CLIENTE
	WHERE
	SEXO = 'M' OR ENDERECO LIKE '%RJ';
	
	SELECT NOME, EMAIL FROM CLIENTE
	WHERE
	SEXO = 'F' OR ENDERECO LIKE '%ESTACIO';
	
/*AND - E*/

	SELECT NOME, EMAIL FROM CLIENTE
	WHERE
	SEXO = 'M' AND ENDERECO LIKE '%RJ';
	
	SELECT NOME, EMAIL FROM CLIENTE
	WHERE
	SEXO = 'F' AND ENDERECO LIKE '%ESTACIO';