/*DATABASE LOJA*/

/*REGRA DE NEGOCIO
REGRA DE NEGOCIO - DEFINIDA PELO GERENTE DE PROJETO OU ANALISTA DE NEGOCIO

** ENDERECO - OBRIGATORIO O CADASTRO DE SOMENTE UM.

** TELEFONE - NAO OBRIGATORIO, POSSO CADASTRAR MAIS DE UM.
*/

/*CRIAR O BANCO DE DADOS*/
CREATE DATABASE LOJA;

/*ATIVAR O BANCO DE DADOS*/
USE LOJA;

/*CRIAR AS TABELAS DO BANCO DE DADOS*/
CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	CPF VARCHAR(15) UNIQUE,
	EMAIL VARCHAR(50) UNIQUE,
	SEXO ENUM('M','F') NOT NULL
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM ('RES','CEL','COM'),
	NUMERO VARCHAR(10),
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);