/*MODELAGEM DE CLIENTE*/

/*DATABASE COMERCIO*/

/*CRIAR BANCO DADOS*/
CREATE DATABASE COMERCIO; 

/*CONECTAR AO BANCO DADOS*/
USE COMERCIO; 

/*CRIAR TABELA CLIENTE*/
CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT, /*INTEIRO CHAVE PRIMARIA COM AUTO INCREMENTO*/
	NOME VARCHAR(30) NOT NULL, /*NOT NULL NAO PODE TER CAMPO NULO*/
	SEXO ENUM('M','F') NOT NULL, /*DEFINE OS VALORES POSSIVEIS DO ATRIBUTO*/
	EMAIL VARCHAR(50) UNIQUE, /*UNIQUE - INF.CADASTRADA E UNICA*/
	CPF VARCHAR(15) UNIQUE
); 

/*CRIAR TABELA TELEFONE*/
CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('COM','RES','CEL'),
	NUMERO VARCHAR(10),
	ID_CLIENTE INT, /*CHAVE ESTRANGEIRA*/
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

/*CRIAR TABELA ENDERECO*/
CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT, /*CHAVE ESTRANGEIRA*/
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

/*FOREING KEY - CHAVE ESTRANGEIRA* - FK*/

/*FK - E A CHAVE PRIMARIA DE UMA TABELA, QUE VAI ATE
OUTRA TABELA FAZER REFERENCIA*/

/*EM RELACIONAMENTOS 1 X 1 , A CHAVE ESTRANGEIRA
FICA NA TABELA MAIS FRACA*/

/*EM RELACIONAMETNOS 1 X N , A CHAVE ESTRANGEIRA
FICARA SEMPRE NA TABELA N*/

/*REFERENCIAR A CHAVE ESTRANGEIRA NA TABELA DEFINIDA*/
FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE)

/*INSERINDO DADOS NA TABELA CLIENTE DO DB COMERCIO*/
INSERT INTO CLIENTE VALUES(NULL,'JOAO','M','JOAO@IG.COM','98547-6');
INSERT INTO CLIENTE VALUES(NULL,'CARLOS','M','CARLOS@TERA.COM','86664-7');
INSERT INTO CLIENTE VALUES(NULL,'ANA','F','ANA@GLOBO.COM','75658-5');
INSERT INTO CLIENTE VALUES(NULL,'JORGE','M','JORGE@IG.COM','88657-5');
INSERT INTO CLIENTE VALUES(NULL,'CLARA','M',NULL,'99754-7');
INSERT INTO CLIENTE VALUES(NULL,'CELIA','F','JOAO@TERRA.COM','77558-5');

SELECT * FROM CLIENTE;

/*INSERINDO UM REGISTRO ERRADO*/

INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','M','JOAO@IG.COM',NULL);

/*CORRIGINDO*/

INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','M',NULL,'78558-6');
INSERT INTO CLIENTE VALUES(NULL,'JOAO','M',NULL,'86695-6');

/*INSERINDO DADOS NA TABELA ENDERECO*/
INSERT INTO ENDERECO VALUES(NULL,'RUA A','CENTRO','B. HORIZONTE','MG',4);
INSERT INTO ENDERECO VALUES(NULL,'RUA B','CENTRO','RIO DE JANEIRO','RJ',1);
INSERT INTO ENDERECO VALUES(NULL,'RUA C','JARDINS','SAO PAULO','SP',3);
INSERT INTO ENDERECO VALUES(NULL,'RUA B','ESTACIO','RIO DE JANEIRO','RJ',8);
INSERT INTO ENDERECO VALUES(NULL,'RUA Z','CRUZEIRO','B. HORIZONTE','MG',2);
INSERT INTO ENDERECO VALUES(NULL,'RUA X','FLAMENGO','RIO DE JANEIRO','RJ',7);
INSERT INTO ENDERECO VALUES(NULL,'RUA Z','CRUZEIRO','B. HORIZONTE','MG',5);
INSERT INTO ENDERECO VALUES(NULL,'RUA X','CENTRO','NITEROI','RJ',6);

/*INSERINDO DADOS NA TABELA TELEFONE*/
INSERT INTO TELEFONE VALUES(NULL,'CEL','3456789',1);
INSERT INTO TELEFONE VALUES(NULL,'COM','3456789',3);
INSERT INTO TELEFONE VALUES(NULL,'CEL','3456789',2);
INSERT INTO TELEFONE VALUES(NULL,'CEL','3456789',7);
INSERT INTO TELEFONE VALUES(NULL,'COM','9876787',1);
INSERT INTO TELEFONE VALUES(NULL,'RES','2324353',6);
INSERT INTO TELEFONE VALUES(NULL,'CEL','2334567',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','8768790',7);
INSERT INTO TELEFONE VALUES(NULL,'RES','3423657',7);
INSERT INTO TELEFONE VALUES(NULL,'CEL','3987698',3);
INSERT INTO TELEFONE VALUES(NULL,'CEL','1345435',6);
INSERT INTO TELEFONE VALUES(NULL,'RES','5678893',6);






























