/*DIA 19/03/2020 - SELECAO, PROJECAO E JUNCAO*/

/*PROJECAO - TUDO QUE QUEREMOS PROJETAR NA TELA*/

SELECT NOW() AS 'DATA';

SELECT NOME, NOW() AS 'DATA' /*PROJECAO*/
FROM CLIENTE;

/*SELECAO - TEORIA DOS CONJUNTOS - WHERE E A CLAUSULA DE SELECAO*/

SELECT NOME, SEXO
FROM CLIENTE;

SELECT NOME, SEXO
FROM CLIENTE
WHERE SEXO = 'M'; /*SELECAO*/

UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE = 5; /*SELECAO*/

/*JUNCAO*/

/*NOME, SEXO, BAIRRO, CIDADE, DATA*/

SELECT NOME, SEXO, BAIRRO, CIDADE, NOW() AS 'DATA' /*PROJECAO*/
FROM CLIENTE, ENDERECO
WHERE IDCLIENTE = ID_CLIENTE /*SELECAO - CLAUSULA DE SELECAO*/
/*ESQUECA WHERE PARA FAZER JOIN - NAO UTILIZE WHERE PARA FAZER JOIN*/
AND BAIRRO = 'CENTRO';

/*JOIN - JUNCAO*/

/*JOIN COM DUAS TABELAS*/

SELECT NOME, SEXO, BAIRRO, CIDADE /*PROJECAO*/
FROM CLIENTE
INNER JOIN ENDERECO /*JUNCAO*/
ON IDCLIENTE = ID_CLIENTE
WHERE BAIRRO = 'CENTRO'; /*SELECAO*/

/*JOIN COM TRES TABELAS*/
/*ID_CLIENTE E UMA CLAUSULA AMBIGUA-APARECE DUAS VEZES NA DECLARACAO*/
SELECT NOME, SEXO, BAIRRO, CIDADE, TIPO, NUMERO
FROM CLIENTE
INNER JOIN ENDERECO
ON IDCLIENTE = ID_CLIENTE /* */
INNER JOIN TELEFONE
ON IDCLIENTE = ID_CLIENTE; /* */

/*CORRIGINDO A AMBIGUIDADE*/
/*JOIN COM CAMPO PERTENCENDO A TABELA(CLIENTE.NOME)*/
SELECT CLIENTE.NOME, CLIENTE.SEXO,
ENDERECO.BAIRRO, ENDERECO.CIDADE,
TELEFONE.TIPO, TELEFONE.NUMERO
FROM CLIENTE
INNER JOIN ENDERECO
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE /* */
INNER JOIN TELEFONE
ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE; /* */

/*OUTRA MANEIRA DE CRIAR A JOIN PARA AMBIGUIDADE*/
/*CRIANDO APELIDOS PARA AS TABELAS*/
SELECT C.NOME, C.SEXO,
E.BAIRRO, E.CIDADE,
T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

/*SELECAO, JUNCAO, PROJECAO*/
SELECT C.NOME, C.SEXO,
E.BAIRRO, E.CIDADE,
T.TIPO, T.NUMERO /*PROJECAO*/
FROM CLIENTE C
INNER JOIN ENDERECO E /*JUNCAO*/
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'M'; /*SELECAO*/



/*REFAZENDO A QUERY*/
SELECT CLIENTE.NOME, CLIENTE.SEXO,
ENDERECO.BAIRRO, ENDERECO.CIDADE,
TELEFONE.TIPO, TELEFONE.NUMERO
FROM CLIENTE
INNER JOIN ENDERECO
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE
ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;

/*REFAZENDO A QUERY*/
SELECT C.NOME, C.SEXO,
E.BAIRRO, E.CIDADE,
T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

/*REVISANDO A QUERY*/
SELECT C.NOME, C.SEXO, C.EMAIL,
E.CIDADE, T.NUMERO 
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F';


































































