/*UTILIZANDO O UPDATE PARA ATUALIZAR VALORES*/

	SELECT NOME, EMAIL
	FROM CLIENTE;
	
	UPDATE CLIENTE
	SET EMAIL = 'LILIAN@HOTMAIL.COM';
	
/*UTILIZAR O UPDATE SEMPRE ACOMPANHADO DA CLAUSULA WHERE*/

	UPDATE CLIENTE
	SET EMAIL = 'ANA@GMAIL.COM'
	WHERE NOME = 'ANA';
	
	UPDATE CLIENTE
	SET EMAIL = 'CARLA@GMAIL.COM'
	WHERE NOME = 'CARLA';